# Generated by Django 3.2 on 2021-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_brand', '0001_initial'),
        ('eshop_products', '0006_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, to='eshop_product_brand.ProductBrand', verbose_name='برند ها'),
        ),
    ]
