# Generated by Django 3.2 on 2021-04-21 10:23

from django.db import migrations, models
import django.utils.timezone
import eshop_blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=eshop_blog.models.upload_image_path, verbose_name='تصویر')),
                ('writer', models.CharField(default='ادمین', max_length=150, verbose_name='نام نمایشی نویسنده')),
                ('tag', models.CharField(max_length=150, verbose_name='تگ ها (با "/" جدا کنید)')),
                ('stars', models.IntegerField(default=5, max_length=5, verbose_name='محبوبیت - ستاره(1 - 5)')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('visit_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
            ],
        ),
    ]
