# Generated by Django 3.2 on 2021-04-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'بلاگ', 'verbose_name_plural': 'وبلاگ'},
        ),
    ]
