# Generated by Django 3.2 on 2021-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='stars',
            field=models.IntegerField(default=5, verbose_name='محبوبیت - ستاره(1 - 5)'),
        ),
    ]
