# Generated by Django 3.2 on 2021-04-25 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_products', '0010_product_visit_count'),
        ('eshop_account', '0003_alter_userinformation_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن')),
                ('interests', models.ManyToManyField(to='eshop_products.Product', verbose_name='علاقه مندی ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'اطلاعات کاربران',
            },
        ),
    ]
