# Generated by Django 3.2 on 2021-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0010_product_visit_count'),
        ('eshop_account', '0004_interestsuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='interests',
            field=models.ManyToManyField(to='eshop_products.Product', verbose_name='علاقه مندی ها'),
        ),
    ]
