# Generated by Django 3.2 on 2021-04-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0005_userinformation_interests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestsUser',
        ),
    ]
