# Generated by Django 3.2 on 2021-05-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0007_forgetpassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgetpassword',
            options={'verbose_name': 'ادرس', 'verbose_name_plural': 'ادرس های فراموشی رمز عبور'},
        ),
    ]
