# Generated by Django 3.2 on 2021-04-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_sitesetting_copy_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bale',
            field=models.URLField(blank=True, null=True, verbose_name='بله'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='insta',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sorosh',
            field=models.URLField(blank=True, null=True, verbose_name='سروش'),
        ),
    ]
