# Generated by Django 3.2 on 2021-04-20 06:11

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0005_siteimagesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimagesetting',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path, verbose_name='ایکون سایت'),
        ),
        migrations.AlterField(
            model_name='siteimagesetting',
            name='mapImage',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path, verbose_name='تصویر نقشه'),
        ),
    ]
