# Generated by Django 3.2 on 2021-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0006_auto_20210420_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='merchantId',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='مرچنت درگاه پرداخت زرین پال'),
        ),
    ]
