# Generated by Django 3.2 on 2021-04-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0007_sitesetting_merchantid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='payDescription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تراکنش'),
        ),
    ]
