# Generated by Django 3.2 on 2021-05-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0008_sitesetting_paydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address_web',
            field=models.URLField(blank=True, help_text='ادرس دامنه سایت. مانند https://www.navidpy.ir/', null=True, verbose_name='ادرس سایت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سایت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تگ های سایت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='verification',
            field=models.URLField(blank=True, null=True, verbose_name='کد وریفای گوگل'),
        ),
    ]
