# Generated by Django 3.2 on 2021-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0009_auto_20210501_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address_web',
            field=models.URLField(blank=True, help_text='ادرس دامنه سایت. مانند /https://www.navidpy.ir', null=True, verbose_name='ادرس سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات نمایشی در گوگل درمورد وبسایت', null=True, verbose_name='توضیحات سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='keywords',
            field=models.CharField(blank=True, help_text="کلمات کلیدی برای متور های جستوجوگر(کلمات را حتما با '،'جدا کنید)", max_length=200, null=True, verbose_name='تگ های سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='verification',
            field=models.CharField(blank=True, help_text='کد گرفته شده از (https://search.google.com/search-console)', max_length=300, null=True, verbose_name='کد وریفای گوگل'),
        ),
    ]
