# Generated by Django 3.2 on 2021-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی ')),
                ('email', models.EmailField(max_length=35, verbose_name='ایمیل ')),
                ('subject', models.CharField(max_length=40, verbose_name='عنوان پیام ')),
                ('text', models.TextField(max_length=500, verbose_name='متن پیام ')),
                ('is_read', models.BooleanField(verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
