# Generated by Django 3.2 on 2021-04-23 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0003_commentsproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsproduct',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='زمان انتشار'),
        ),
    ]
