# Generated by Django 3.2 on 2021-04-27 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0006_commentsproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsproduct',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
    ]
