# Generated by Django 3.2 on 2021-04-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trackingCode',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='کد پیگیری'),
        ),
    ]
