# Generated by Django 3.2 on 2021-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0003_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': ' کد تخفیف', 'verbose_name_plural': 'کد های تخفیف'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد'),
        ),
    ]
