# Generated by Django 3.2 on 2021-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات برند'),
        ),
    ]
